import { StyleSheet } from "react-native";

import type { AppTheme } from "../theme/colors";

export function createHomeStyles(theme: AppTheme) {
  const { colors } = theme;

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.background,
    },
    keyboardAvoidingView: {
      flex: 1,
    },
    contentScroll: {
      flex: 1,
    },
    backgroundLayer: {
      ...StyleSheet.absoluteFillObject,
    },
    backgroundTopFade: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: "58%",
      backgroundColor: colors.backgroundTop,
    },
    backgroundBottomFade: {
      position: "absolute",
      top: "42%",
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: colors.backgroundBottom,
    },
    backgroundOrbPrimary: {
      position: "absolute",
      top: 28,
      right: -34,
      width: 168,
      height: 168,
      borderRadius: 84,
      backgroundColor: colors.orbPrimary,
    },
    backgroundOrbSecondary: {
      position: "absolute",
      top: 180,
      left: -46,
      width: 118,
      height: 118,
      borderRadius: 59,
      backgroundColor: colors.orbSecondary,
    },
    content: {
      flexGrow: 1,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 20,
    },
    header: {
      alignItems: "center",
      marginTop: 8,
      marginBottom: 18,
    },
    emoji: {
      fontSize: 28,
      marginBottom: 6,
    },
    title: {
      fontSize: 26,
      fontWeight: "800",
      color: colors.text,
      marginBottom: 6,
    },
    subtitle: {
      fontSize: 15,
      color: colors.textMuted,
      textAlign: "center",
      lineHeight: 21,
      maxWidth: 280,
    },
    themeToggle: {
      flexDirection: "row",
      gap: 8,
      marginTop: 14,
      padding: 4,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    themeToggleButton: {
      minHeight: 30,
      borderRadius: 15,
      paddingHorizontal: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    themeToggleButtonActive: {
      backgroundColor: colors.primary,
    },
    themeToggleButtonText: {
      fontSize: 13,
      fontWeight: "800",
      color: colors.textMuted,
    },
    themeToggleButtonTextActive: {
      color: colors.textOnPrimary,
    },
    infoCard: {
      backgroundColor: colors.surfaceSoft,
      borderRadius: 18,
      paddingVertical: 14,
      paddingHorizontal: 18,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: colors.border,
    },
    infoGrid: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 16,
    },
    infoMetric: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: colors.border,
    },
    infoLabel: {
      fontSize: 13,
      color: colors.textMuted,
      marginBottom: 4,
    },
    infoValue: {
      fontSize: 28,
      fontWeight: "800",
      color: colors.primary,
    },
    categoryTabsContainer: {
      marginBottom: 14,
    },
    categoryTabsContent: {
      gap: 8,
      paddingRight: 4,
    },
    categoryChip: {
      minHeight: 38,
      borderRadius: 19,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    categoryChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary,
    },
    categoryChipPressed: {
      opacity: 0.78,
    },
    categoryChipNew: {
      borderStyle: "dashed",
      backgroundColor: colors.surfaceAlt,
    },
    categoryChipText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text,
    },
    categoryChipTextActive: {
      color: colors.textOnPrimary,
    },
    categoryChipNewText: {
      fontSize: 14,
      fontWeight: "800",
      color: colors.primary,
    },
    categoryForm: {
      marginBottom: 14,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      padding: 12,
    },
    categoryInput: {
      minHeight: 42,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.inputBackground,
      paddingHorizontal: 12,
      fontSize: 15,
      fontWeight: "600",
      color: colors.text,
    },
    categoryFormActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 8,
      marginTop: 10,
    },
    categoryActionButton: {
      minHeight: 36,
      borderRadius: 18,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
    },
    categoryActionButtonPrimary: {
      backgroundColor: colors.primary,
    },
    categoryActionButtonSecondary: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    categoryActionButtonPrimaryText: {
      fontSize: 14,
      fontWeight: "800",
      color: colors.textOnPrimary,
    },
    categoryActionButtonSecondaryText: {
      fontSize: 14,
      fontWeight: "800",
      color: colors.text,
    },
    calendarToolbar: {
      flexDirection: "row",
      justifyContent: "flex-end",
      marginBottom: 8,
    },
    todayButton: {
      minHeight: 34,
      borderRadius: 17,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceAlt,
    },
    todayButtonText: {
      fontSize: 14,
      fontWeight: "800",
      color: colors.primary,
    },
    calendarCard: {
      backgroundColor: colors.calendarBackground,
      borderRadius: 24,
      padding: 12,
      shadowColor: colors.shadow,
      shadowOpacity: theme.mode === "dark" ? 0.22 : 0.08,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    notesCard: {
      marginTop: 12,
      marginBottom: 20,
      backgroundColor: colors.surface,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 18,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: theme.mode === "dark" ? 0.2 : 0.06,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 3 },
      elevation: 3,
    },
    notesHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      paddingTop: 2,
      paddingBottom: 4,
    },
    notesHeaderText: {
      flex: 1,
    },
    notesTitle: {
      fontSize: 17,
      fontWeight: "800",
      color: colors.text,
    },
    notesDate: {
      marginTop: 2,
      fontSize: 13,
      fontWeight: "600",
      color: colors.textMuted,
    },
    notesCloseButton: {
      minHeight: 34,
      borderRadius: 17,
      paddingHorizontal: 12,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceAlt,
    },
    notesCloseButtonText: {
      fontSize: 13,
      fontWeight: "800",
      color: colors.primary,
    },
    emojiSection: {
      marginTop: 14,
    },
    emojiSectionLabel: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.textMuted,
      marginBottom: 8,
    },
    emojiOptionsRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: 8,
    },
    emojiOption: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceAlt,
    },
    emojiOptionSelected: {
      borderColor: colors.primary,
      backgroundColor: colors.surfaceSoft,
    },
    emojiOptionText: {
      fontSize: 20,
    },
    emojiRemoveButton: {
      minHeight: 38,
      borderRadius: 19,
      paddingHorizontal: 12,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    emojiRemoveButtonText: {
      fontSize: 13,
      fontWeight: "800",
      color: colors.textMuted,
    },
    notesInput: {
      minHeight: 112,
      marginTop: 14,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.inputBackground,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 15,
      lineHeight: 21,
      color: colors.text,
    },
    loadingBox: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    loadingText: {
      fontSize: 18,
      color: colors.text,
      fontWeight: "600",
    },
    dayPressable: {
      width: 52,
      height: 52,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
      overflow: "visible",
    },
    dayPressablePressed: {
      opacity: 0.78,
      transform: [{ scale: 0.95 }],
    },
    dayContainer: {
      width: 46,
      height: 46,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
      overflow: "visible",
    },
    dayCircle: {
      width: 40,
      height: 40,
      borderRadius: 20,
      overflow: "hidden",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    dayCircleSelected: {
      borderWidth: 2,
      borderColor: colors.primaryMuted,
      backgroundColor: colors.surfaceAlt,
    },
    dayCircleChecked: {
      backgroundColor: colors.primary,
      width: 40,
      height: 40,
      borderRadius: 20,
      overflow: "hidden",
    },
    dayCircleCheckedSelected: {
      borderWidth: 2,
      borderColor: colors.border,
    },
    dayCircleToday: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 2,
      borderColor: colors.primary,
      overflow: "hidden",
      backgroundColor: colors.surfaceAlt,
    },
    dayCircleTodayChecked: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 2,
      borderColor: colors.primaryMuted,
      overflow: "hidden",
      backgroundColor: colors.primary,
    },
    dayNumber: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.text,
    },
    dayNumberChecked: {
      color: colors.textOnPrimary,
      fontWeight: "700",
    },
    dayNumberToday: {
      color: colors.primary,
      fontWeight: "800",
    },
    dayNumberTodayChecked: {
      color: colors.textOnPrimary,
      fontWeight: "800",
    },
    dayNumberDisabled: {
      color: colors.disabledText,
    },
    checkBadge: {
      position: "absolute",
      bottom: 2,
      right: 2,
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: colors.success,
      alignItems: "center",
      justifyContent: "center",
    },
    checkIcon: {
      fontSize: 10,
      fontWeight: "900",
      color: colors.successText,
    },
    dayEmojiBadge: {
      position: "absolute",
      top: 1,
      right: 1,
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.emojiBadgeBackground,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: theme.mode === "dark" ? 0.18 : 0.1,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
    dayEmojiText: {
      fontSize: 12,
      lineHeight: 15,
      textAlign: "center",
      includeFontPadding: false,
    },
  });
}
