import { StyleSheet } from "react-native";

const PRIMARY_BLUE = "#2563eb";
const SOFT_BLUE = "#dbeafe";
const TEXT_DARK = "#1e3a8a";
const TEXT_MUTED = "#64748b";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundTopFade: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "58%",
    backgroundColor: "#eaf3ff",
  },
  backgroundBottomFade: {
    position: "absolute",
    top: "42%",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#ffffff",
  },
  backgroundOrbPrimary: {
    position: "absolute",
    top: 28,
    right: -34,
    width: 168,
    height: 168,
    borderRadius: 84,
    backgroundColor: "rgba(37, 99, 235, 0.08)",
  },
  backgroundOrbSecondary: {
    position: "absolute",
    top: 180,
    left: -46,
    width: 118,
    height: 118,
    borderRadius: 59,
    backgroundColor: "rgba(147, 197, 253, 0.08)",
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  header: {
    alignItems: "center",
    marginTop: 8,
    marginBottom: 18,
  },
  emoji: {
    fontSize: 28,
    marginBottom: 6,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: TEXT_DARK,
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 15,
    color: TEXT_MUTED,
    textAlign: "center",
    lineHeight: 21,
    maxWidth: 280,
  },
  infoCard: {
    backgroundColor: SOFT_BLUE,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  infoGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
  },
  infoMetric: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  infoLabel: {
    fontSize: 13,
    color: TEXT_MUTED,
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 28,
    fontWeight: "800",
    color: PRIMARY_BLUE,
  },
  calendarCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 12,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  notesSheet: {
    marginTop: 12,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
    borderWidth: 1,
    borderColor: "#bfdbfe",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  notesSheetExpanded: {
    paddingBottom: 16,
  },
  notesHeader: {
    alignItems: "center",
    gap: 8,
  },
  notesHandle: {
    width: 44,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#bfdbfe",
  },
  notesTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: TEXT_DARK,
    textAlign: "center",
  },
  notesDate: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: "600",
    color: TEXT_MUTED,
    textAlign: "center",
  },
  notesInput: {
    minHeight: 112,
    marginTop: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#bfdbfe",
    backgroundColor: "#f8fbff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    lineHeight: 21,
    color: "#0f172a",
  },
  loadingBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    fontSize: 18,
    color: TEXT_DARK,
    fontWeight: "600",
  },
  dayPressable: {
    width: 52,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  dayPressablePressed: {
    opacity: 0.78,
    transform: [{ scale: 0.95 }],
  },
  dayContainer: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  dayCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  dayCircleChecked: {
    backgroundColor: PRIMARY_BLUE,
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: "hidden",
  },
  dayCircleToday: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: PRIMARY_BLUE,
    overflow: "hidden",
    backgroundColor: "#f8fbff",
  },
  dayCircleTodayChecked: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#93c5fd",
    overflow: "hidden",
    backgroundColor: PRIMARY_BLUE,
  },
  dayNumber: {
    fontSize: 15,
    fontWeight: "600",
    color: "#0f172a",
  },
  dayNumberChecked: {
    color: "#ffffff",
    fontWeight: "700",
  },
  dayNumberToday: {
    color: "#2563eb",
    fontWeight: "800",
  },
  dayNumberTodayChecked: {
    color: "#ffffff",
    fontWeight: "800",
  },
  dayNumberDisabled: {
    color: "#cbd5e1",
  },
  checkBadge: {
    position: "absolute",
    bottom: 2,
    right: 2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#86efac",
    alignItems: "center",
    justifyContent: "center",
  },
  checkIcon: {
    fontSize: 10,
    fontWeight: "900",
    color: "#065f46",
  },
});
